[alembic]
script_location = migrations
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
version_path_separator = os

sqlalchemy.url = mysql+pymysql://root:rootpassword@localhost:3306/library_db

[logging]
default_level = INFO
